# Generated by Django 5.1.4 on 2024-12-31 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AreaMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AreaName', models.CharField(max_length=40)),
                ('CityName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.citymst')),
            ],
        ),
    ]
