# Generated by Django 5.1.4 on 2025-01-11 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0003_alter_citymst_options_usermst_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermst',
            name='Img',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.CreateModel(
            name='SalonMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=20)),
                ('Img', models.ImageField(default='default.jpg', upload_to='')),
                ('Status', models.CharField(max_length=10)),
                ('OpenTime', models.TimeField()),
                ('CloseTime', models.TimeField()),
                ('Type', models.CharField(max_length=10)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.areamst')),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.citymst')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.usermst')),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.servicemst')),
            ],
        ),
    ]
