# Generated by Django 5.1.4 on 2025-01-17 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0004_alter_usermst_img_salonmst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonmst',
            name='Service',
        ),
        migrations.CreateModel(
            name='SelectedServicemsMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField()),
                ('SalonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.salonmst')),
                ('ServiceName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.servicemst')),
            ],
        ),
    ]
