# Generated by Django 5.1.4 on 2025-01-23 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0005_remove_salonmst_service_selectedservicemsmst'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(default='default.jpg', upload_to='')),
                ('SalonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.salonmst')),
            ],
        ),
    ]
