# Generated by Django 5.1.4 on 2025-01-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0006_imagemst'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonmst',
            name='NumberOfSeats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
