# Generated by Django 5.1.4 on 2025-02-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0007_salonmst_numberofseats'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotBookingMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingDate', models.DateField()),
                ('TimeSlote', models.CharField(max_length=10)),
                ('BillAmount', models.IntegerField()),
                ('SalonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.salonmst')),
                ('ServiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.selectedservicemsmst')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.usermst')),
            ],
        ),
    ]
