# Generated by Django 5.1.4 on 2025-02-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0009_alter_slotbookingmst_timeslote'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbookingmst',
            name='Status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
