# Generated by Django 5.1.4 on 2025-03-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0010_slotbookingmst_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermst',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
